---
production: &default
  serverPort: 5555
  baseUrl: http://controlarc.axionline.com
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    livereload: false
    minify: true
    css:
      stylusPreCompile: true
      compress: true
  languages:
    default: es
    list: [en, es]
  security:
    secret: c0ntr0larc.dev
  session:
    cookieDomain: .controlarc.dev
    maxAge: 259200
    cookiePrefix: 'mdSession_'
    path: '/'
    httpOnly: true

stage: &stage
  <<: *default
  baseUrl: stage.controlarc.dev

latest: &latest
  <<: *stage
  baseUrl: latest.controlarc.dev

development:
  <<: *default
  baseUrl: http://localhost
  serverPort: 3333
  html:
    livereload: true
    minify: false
    css:
        stylusPreCompile: false
        compress: false